project:
  type: website
  output-dir: docs

website:
  title: "RohithJavvadi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hobbies.qmd
      - skills.qmd
      - projects.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



